### ISSUE TITLE
Need Some Information

### ISSUE THREAD

**Issue by rasgharpuredata** [anukriti-ranjan/csv_agent#1]
Hey, been reviewing your project, very nice approach, Just need some information regarding something, I need to calaculate token usage from open ai and need to save image in local folder

**Comment by anukriti-ranjan** [comment]
1) calculating token usage from open ai:

I am using instructor for getting response in the specified pydantic schema. Instructor does have an api for giving the prompt and completion token count. client.chat.completions.create_with_completion (instead of client.chat.completions.create currently used in the code. 

e.g 
        model_response, completion = self.client.chat.completions.create_with_completion(
            model="gpt-3.5-turbo",
            max_retries=self.max_retries_first_response,
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature = self.temperarure,
            response_model=PythonCodeForDataFrame,
        )

completion.usage will them provide you with the token count.

2) Saving image to local folder.

You can use this function:
def save_plots(plot_data, save_path, file_format='png'):
    """
    Saves plots encoded in base64 to specified format and path.
    
    Args:
    - plot_data: List of base64-encoded strings of plot images.
    - save_path: Directory to save the plot images.
    - file_format: Format of the saved image files ('png' or 'jpeg').
    """
    for i, plot_encoded in enumerate(plot_data):
        image_data = base64.b64decode(plot_encoded)
        image = Image.open(BytesIO(image_data))
        image.save(f"{save_path}/plot_{i+1}.{file_format}", file_format.upper())
        
Once you check for the key "plot_data" in the result is non empty, the above function can be invoked.

I'll push these changes soon.

**Comment by rasgharpuredata** [comment]
Thanks For the Feedback @anukriti-ranjan ,I replaced exiting memory with langchain Memory, it is working perfectly, just a suggestion, how can we make responses more readable like langchain agents, Currently it does only give a word to word answer without any explanation, can we improve that ? waiting for your feedback

**Comment by anukriti-ranjan** [comment]
Thanks for the suggestion.
A get_result_summary method can be added to the agent class. When the generated code is executed , it is checked for whether it contains list, dict , dataframe etc.
```
            if "dict" in final_result:
                answer = str(final_result.get("dict"))
                context += "\n" + f"Answer to the query: {answer}"
            if "list" in final_result:
                answer = str(final_result.get("list"))
                context += "\n" + f"Answer to the query: {answer}"
            if "result_value" in final_result:
                answer = str(final_result.get("result_value"))
                context += "\n" + f"Answer to the query: {answer}"
            if "dataframe" in final_result:
                final_result_df_head = str(final_result.get("dataframe").head(5).to_markdown())
                context += "\n" + f"Answer to the query: The first few rows of the generated answer: \n{final_result_df_head}"
            if "pandas_series" in final_result:
                final_result_df_head = str(final_result.get("pandas_series").head(5).to_markdown())
                context += "\n" + f"Answer to the query: The first few rows of the generated answer: \n{final_result_df_head}"
            if "plot_data" in final_result:
                context += "\n" + f"Answer to the query: A figure was plotted."
```
after this step , another method can be called that makes another LLM call to get the answer summary by sending the response of the executed code to it in all cases except when the final_result contains error or plot_data.  and instead of returning final_result (executed code output) in get_answer_to_query method, the output of this LLM call can be returned.
the prompt can be :
final_answer_summary_prompt = """
{DATAFRAME_PROMPT}
query: {user_query}
generated_code : {python_code}
result of generated_code: {final_result}
Based on the above, the answer to the user query is:
"""

Will try and make these changes to the code soon.

**Comment by rasgharpuredata** [comment]
Thanks for your speedy response, Goodluck with this project, Hoping to see changes real soon.

**Comment by rasgharpuredata** [comment]
btw, I am interested to collaborate on this project. Let me know, @anukriti-ranjan
